#line 2 "D:/graphics/nprojects/safegi/final_pack/SafeGI/typed/libs/sparser/scanner.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 96
#define YY_END_OF_BUFFER 97
static yyconst short int yy_accept[394] =
    {   0,
        0,    0,   86,   86,    0,    0,    0,    0,   97,   84,
       83,   82,   68,   50,   51,   56,   57,   66,   58,   67,
       59,   73,   72,   65,   61,   40,   62,   84,   81,   52,
       53,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   54,   55,   86,   96,   87,   90,
       91,   94,   93,   94,   83,    0,   73,   72,    0,    0,
       77,   85,   89,   76,   73,    0,    0,   73,    0,   72,
       72,   63,   60,   64,    0,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   69,   36,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,

       81,   81,   81,   81,   81,   86,   87,   87,   88,   93,
        0,    0,    0,    0,   77,   75,    0,   76,    0,   78,
       74,    0,    0,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   71,   81,    5,   81,   81,   81,
       37,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   95,    0,    0,    0,   77,    0,   75,    0,
       76,   78,   74,    0,   81,   81,   81,   81,   81,   81,
        8,   81,   70,   81,   81,   81,   81,   81,   16,   10,
       81,   81,   81,   79,    6,   81,   81,   81,   81,    9,
        4,    0,    0,    0,   75,   92,   81,   81,   81,   81,

       81,   81,   81,   14,   80,    7,   38,   81,   13,   81,
       81,   81,   81,   81,   81,   81,   15,   81,    0,    0,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   16,
       10,   39,   81,   81,   81,   81,   81,   48,   49,   81,
       81,   81,   81,   45,   81,   81,   81,   81,   81,   81,
        2,   81,    1,   81,   81,   81,   81,   81,   42,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   46,   81,
       81,   81,   41,    3,   81,   81,   81,   81,   81,   17,
       11,   19,   81,   81,   12,   81,   81,   81,   81,   81,
       81,   81,   81,   24,   24,   25,   81,   81,   81,   81,

       18,   18,   81,   81,   81,   81,   30,   30,   31,   81,
       81,   47,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   23,   81,   81,   20,   81,   81,   81,   81,   81,
       81,   81,   81,   29,   81,   81,   26,   81,   81,   81,
       81,   81,   81,   35,   81,   81,   32,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   21,   22,   81,   81,
       81,   81,   44,   43,   81,   81,   27,   28,   17,   81,
       81,   81,   81,   81,   33,   34,   24,   81,   17,   81,
       81,   30,   81,   81,   23,   81,   81,   29,   81,   35,
       81,   21,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    1,    1,    5,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   18,   18,   19,   19,    1,   20,   21,
       22,   23,    1,   24,   25,   26,   27,   28,   29,   30,
       31,   31,   31,   31,   31,   31,   32,   31,   31,   31,
       31,   33,   34,   31,   35,   31,   31,   36,   31,   31,
       37,    1,   38,    1,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   31,   31,   49,   50,   51,
       52,   53,   31,   54,   55,   56,   57,   58,   59,   60,
       61,   31,   62,    1,   63,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[64] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    1,    1,
        4,    1,    5,    5,    5,    5,    5,    5,    5,    1,
        1,    1,    1,    6,    7,    7,    7,    7,    8,    9,
       10,   10,   10,   10,   10,   10,    1,    1,   10,    7,
        7,    7,   11,    8,    9,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   12,   10,   10,   10,   10,   10,
       10,    1,    1
    } ;

static yyconst short int yy_base[407] =
    {   0,
        0,    0,   61,   62,  673,  672,   64,   68,  674,  677,
      671,  677,  677,  677,  677,  677,   66,  677,   62,   73,
       86,  107,  157,  677,  650,  649,  648,    0,    0,  677,
      677,   54,  613,   42,  619,   59,   58,  627,  609,  621,
      624,   58,   79,   88,  677,  677,    0,  677,  107,  677,
      677,  677,  136,  653,  660,  131,    0,    0,  613,  607,
      133,  677,  677,  136,   71,  150,  189,  677,    0,    0,
      677,  677,  677,  677,  635,    0,  601,  605,  612,  602,
      593,  597,  600,  607,  595,  600,  596,  593,    0,   20,
      606,  601,  588,  587,  586,  591,  580,  582,  587,  589,

      596,  591,  580,  591,  584,    0,  145,  146,  677,  152,
      607,  580,  589,  202,  677,  193,  216,  677,  226,  233,
      125,  604,  617,  578,  574,  579,  579,  569,  567,  571,
      577,  574,  562,  576,    0,  558,    0,  564,  571,  168,
        0,  555,  558,  554,  565,  552,  562,  556,  563,  543,
      172,  560,  677,  558,  559,  240,  251,  269,  677,  276,
      284,  677,  677,  590,  550,  540,  152,  543,  552,  547,
        0,  245,    0,  550,  537,  536,  538,  256,  530,  529,
      534,  538,  529,    0,    0,  533,  531,  259,  535,    0,
        0,  531,  537,  291,  302,  677,  524,  535,   86,  527,

      537,  526,  534,    0,    0,    0,    0,  525,    0,  180,
      556,  521,  527,  516,  515,  519,    0,  516,  556,  555,
      525,  512,  514,  508,  516,  503,  518,  500,  512,    0,
        0,    0,  501,  510,  503,  508,  505,  677,  677,  502,
      493,  498,  507,    0,  494,  492,  488,  489,  297,  527,
        0,  487,    0,  489,  491,  494,  495,  482,    0,  491,
      311,  506,  505,  504,  474,  473,  501,  319,    0,  476,
      476,  482,    0,    0,  497,  496,  495,  465,  464,  202,
      343,    0,  475,  478,    0,  490,  480,  476,  444,  443,
      444,  455,  451,  464,  311,    0,  432,  425,  411,  410,

      677,    0,  413,  402,  400,  400,  418,  325,    0,  358,
      360,    0,  360,  359,  344,  362,  350,  348,  348,  337,
      349,  363,  345,  341,    0,  330,  348,  337,  335,  335,
      327,  323,  319,  347,  329,  326,    0,  329,  324,  312,
      309,  310,  309,  337,  319,  316,    0,  307,  304,  315,
      300,  297,  298,  281,  289,  286,  305,    0,  291,  276,
      272,  268,    0,    0,  219,  174,    0,    0,  191,  154,
      171,  162,  137,  139,    0,    0,    0,  150,    0,  108,
      119,    0,  116,   74,    0,   90,   54,    0,   52,    0,
       42,    0,  677,  404,  416,  428,  437,  443,  451,  463,

      475,  483,  488,  494,  498,  505
    } ;

static yyconst short int yy_def[407] =
    {   0,
      393,    1,  394,  394,  395,  395,  396,  396,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  397,  393,
      393,  393,  393,  393,  393,  393,  393,  398,  399,  393,
      393,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  393,  393,  400,  393,  401,  393,
      393,  393,  393,  393,  393,  393,   22,   23,  393,  393,
      402,  393,  393,  403,   22,  404,  393,  393,  405,   23,
      393,  393,  393,  393,  406,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,

      399,  399,  399,  399,  399,  400,  401,  401,  393,  393,
      393,  393,  393,  393,  393,  403,  393,  393,  393,  393,
      405,  406,  393,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  393,  393,  393,  393,  393,  399,  399,  399,  399,

      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  393,  393,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  393,  393,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,

      393,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,    0,  393,  393,  393,  393,  393,  393,  393,

      393,  393,  393,  393,  393,  393
    } ;

static yyconst short int yy_nxt[741] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   23,   23,   23,   23,   23,   24,
       25,   26,   27,   28,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   30,   31,   32,   33,
       34,   29,   29,   35,   36,   29,   29,   37,   29,   38,
       29,   39,   29,   40,   41,   42,   43,   44,   29,   29,
       29,   45,   46,   48,   48,   53,   53,   49,   49,   53,
       53,  136,   56,   54,   57,  137,   56,   54,   57,   58,
       58,   58,   58,   58,   58,   61,   61,   61,   61,   61,
       61,   61,   62,   83,   77,   78,   79,   63,   86,   84,

      392,   97,   89,  391,   59,   80,  393,   87,   90,   81,
       88,   98,   91,  108,  390,   92,   60,   64,  109,   65,
       65,   65,   65,   65,   65,   66,   99,  103,  223,  100,
      393,  104,  389,  101,  388,   67,  102,  110,  110,  105,
      224,   68,   69,   61,   61,   61,   61,   61,   61,   61,
       67,  393,  108,  110,  110,  387,  393,  109,  386,  163,
       64,  114,  115,   68,  117,  118,   69,   64,  385,   70,
       70,   70,   70,   70,   70,   70,  114,  115,   67,  117,
      118,  163,  179,  179,  180,   67,  190,  190,  190,  384,
      199,   71,  383,   67,  230,  230,  119,  382,  119,  200,

       67,  120,  120,  120,  120,  120,  120,  120,  381,  156,
      380,  156,  379,   71,  157,  157,  157,  157,  157,  157,
      157,  158,  159,  160,  300,  160,  299,  378,  161,  161,
      161,  161,  161,  161,  161,  300,  158,  159,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  157,  157,  157,  157,  157,  157,  157,  204,
      204,  204,  162,  157,  157,  157,  157,  157,  157,  157,
      209,  209,  209,  217,  217,  217,  194,  162,  194,  377,
      115,  195,  195,  195,  195,  195,  195,  195,  161,  161,
      161,  161,  161,  161,  161,  115,  161,  161,  161,  161,

      161,  161,  161,  195,  195,  195,  195,  195,  195,  195,
      262,  263,  264,  118,  195,  195,  195,  195,  195,  195,
      195,  376,  265,  266,  275,  276,  277,  375,  118,  374,
      373,  159,  286,  287,  288,  315,  278,  279,  372,  371,
      370,  369,  316,  317,  289,  290,  159,  301,  301,  326,
      301,  368,  367,  366,  365,  364,  327,  328,  363,  362,
      361,  360,  359,  358,  357,  356,  355,  302,  354,  353,
      352,  351,  350,  349,  303,  304,  302,  348,  347,  346,
      345,  344,  302,  343,  342,  302,  341,  340,  339,  302,
      338,  337,  336,  335,  302,  334,  302,  333,  332,  331,

      330,  302,  329,  302,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       58,   58,  326,  325,  324,  323,  322,   58,   58,   75,
       75,   75,   75,   75,   75,   76,  321,   76,   76,   76,
       76,   76,   76,  106,  320,  319,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  107,  318,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,   61,  315,  314,
       61,   61,  116,  313,  312,  116,  116,   66,   66,  311,

      310,   66,  121,  309,  121,  121,  121,  308,  121,  122,
      122,  122,  122,  122,  122,  122,  122,  307,  306,  305,
      298,  297,  296,  295,  294,  293,  292,  291,  285,  284,
      283,  282,  281,  280,  274,  273,  272,  271,  270,  269,
      268,  267,  261,  260,  259,  258,  257,  256,  255,  254,
      253,  252,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  237,  236,  235,  234,
      233,  232,  231,  229,  228,  227,  226,  225,  222,  221,
      220,  219,  218,  216,  215,  214,  213,  212,  211,  210,
      208,  207,  206,  205,  203,  202,  201,  198,  197,  196,

      193,  192,  191,  189,  188,  187,  186,  185,  184,  183,
      182,  181,  178,  177,  176,  175,  174,  173,  172,  171,
      170,  169,  168,  167,  166,  165,  164,  123,  155,  154,
      153,  152,  151,  150,  149,  148,  147,  146,  145,  144,
      143,  142,  141,  140,  139,  138,  135,  134,  133,  132,
      131,  130,  129,  128,  127,  126,  125,  124,  123,  113,
      112,   55,  111,   96,   95,   94,   93,   85,   82,   74,
       73,   72,   55,  393,   51,   51,    9,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,

      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393
    } ;

static yyconst short int yy_chk[741] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,    7,    7,    3,    4,    8,
        8,   90,   19,    7,   19,   90,   17,    8,   17,   17,
       17,   17,   17,   17,   17,   20,   20,   20,   20,   20,
       20,   20,   21,   34,   32,   32,   32,   21,   36,   34,

      391,   42,   37,  389,   19,   32,   65,   36,   37,   32,
       36,   42,   37,   49,  387,   37,   19,   22,   49,   22,
       22,   22,   22,   22,   22,   22,   43,   44,  199,   43,
       65,   44,  386,   43,  384,   22,   43,   53,   53,   44,
      199,   22,   22,   56,   56,   56,   56,   56,   56,   56,
       22,  107,  108,  110,  110,  383,  107,  108,  381,  121,
       66,   61,   61,   22,   64,   64,   22,   23,  380,   23,
       23,   23,   23,   23,   23,   23,   61,   61,   66,   64,
       64,  121,  140,  140,  140,   23,  151,  151,  151,  378,
      167,   23,  374,   66,  210,  210,   67,  373,   67,  167,

       23,   67,   67,   67,   67,   67,   67,   67,  372,  114,
      371,  114,  370,   23,  114,  114,  114,  114,  114,  114,
      114,  116,  116,  117,  369,  117,  280,  366,  117,  117,
      117,  117,  117,  117,  117,  280,  116,  116,  119,  119,
      119,  119,  119,  119,  119,  120,  120,  120,  120,  120,
      120,  120,  156,  156,  156,  156,  156,  156,  156,  172,
      172,  172,  120,  157,  157,  157,  157,  157,  157,  157,
      178,  178,  178,  188,  188,  188,  158,  120,  158,  365,
      157,  158,  158,  158,  158,  158,  158,  158,  160,  160,
      160,  160,  160,  160,  160,  157,  161,  161,  161,  161,

      161,  161,  161,  194,  194,  194,  194,  194,  194,  194,
      249,  249,  249,  161,  195,  195,  195,  195,  195,  195,
      195,  362,  249,  249,  261,  261,  261,  361,  161,  360,
      359,  195,  268,  268,  268,  295,  261,  261,  357,  356,
      355,  354,  295,  295,  268,  268,  195,  281,  281,  308,
      281,  353,  352,  351,  350,  349,  308,  308,  348,  346,
      345,  344,  343,  342,  341,  340,  339,  281,  338,  336,
      335,  334,  333,  332,  281,  281,  281,  331,  330,  329,
      328,  327,  281,  326,  324,  281,  323,  322,  321,  281,
      320,  319,  318,  317,  281,  316,  281,  315,  314,  313,

      311,  281,  310,  281,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      397,  397,  307,  306,  305,  304,  303,  397,  397,  398,
      398,  398,  398,  398,  398,  399,  300,  399,  399,  399,
      399,  399,  399,  400,  299,  298,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  401,  297,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  402,  294,  293,
      402,  402,  403,  292,  291,  403,  403,  404,  404,  290,

      289,  404,  405,  288,  405,  405,  405,  287,  405,  406,
      406,  406,  406,  406,  406,  406,  406,  286,  284,  283,
      279,  278,  277,  276,  275,  272,  271,  270,  267,  266,
      265,  264,  263,  262,  260,  258,  257,  256,  255,  254,
      252,  250,  248,  247,  246,  245,  243,  242,  241,  240,
      237,  236,  235,  234,  233,  229,  228,  227,  226,  225,
      224,  223,  222,  221,  220,  219,  218,  216,  215,  214,
      213,  212,  211,  208,  203,  202,  201,  200,  198,  197,
      193,  192,  189,  187,  186,  183,  182,  181,  180,  179,
      177,  176,  175,  174,  170,  169,  168,  166,  165,  164,

      155,  154,  152,  150,  149,  148,  147,  146,  145,  144,
      143,  142,  139,  138,  136,  134,  133,  132,  131,  130,
      129,  128,  127,  126,  125,  124,  123,  122,  113,  112,
      111,  105,  104,  103,  102,  101,  100,   99,   98,   97,
       96,   95,   94,   93,   92,   91,   88,   87,   86,   85,
       84,   83,   82,   81,   80,   79,   78,   77,   75,   60,
       59,   55,   54,   41,   40,   39,   38,   35,   33,   27,
       26,   25,   11,    9,    6,    5,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,

      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#define INITIAL 0
/* no include is allowed. */
#define YY_NEVER_INTERACTIVE 1
#line 9 "scanner.l"
#include "aux_data.h"
#include<parser.hpp>
#include<assert.h>
//#define PRINT_TOKEN

#define PROCESS_TOKEN(TOKEN) {yylval.str = new string(yytext); PRINT_T(#TOKEN); return TOKEN;}
#define PROCESS_CHAR() {return yytext[0];}
#define PROCESS_NODATA(TOKEN) {return TOKEN;}
//#define PROCESS_TYPE(TYPE) { yylval.type = new gs_type(yytext); yylval.type->src = yytext; PRINT_T(#TYPE); return TYPE;}

#ifdef PRINT_TOKEN
#define PRINT_T(TOKEN) printf("%s: %s\n", TOKEN, yytext)
#else
#define PRINT_T(TOKEN)
#endif

#define T_RESERVED { printf("%s is reserved keyword\n", yytext); }

    string raw_code_source;
#define comment 1

#define cpp_comment 2

#define raw_code 3

#line 692 "D:/graphics/nprojects/safegi/final_pack/SafeGI/typed/libs/sparser/scanner.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 34 "scanner.l"


#line 846 "D:/graphics/nprojects/safegi/final_pack/SafeGI/typed/libs/sparser/scanner.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 394 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 677 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 36 "scanner.l"
PROCESS_NODATA(T_VARY)
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 37 "scanner.l"
PROCESS_NODATA(T_UNIF)
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 38 "scanner.l"
PROCESS_NODATA(T_ATTR)
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 40 "scanner.l"
PROCESS_TOKEN(T_VOID)
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 41 "scanner.l"
PROCESS_TOKEN(T_INT)
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 42 "scanner.l"
PROCESS_TOKEN(T_UINT)
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 43 "scanner.l"
PROCESS_TOKEN(T_FLOAT)
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 44 "scanner.l"
PROCESS_TOKEN(T_BOOL)
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 45 "scanner.l"
PROCESS_TOKEN(T_VEC)
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 46 "scanner.l"
PROCESS_TOKEN(T_MAT4)
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 47 "scanner.l"
PROCESS_NODATA(T_SAMPLER2D_TYPE)
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 48 "scanner.l"
PROCESS_NODATA(T_TEXTURE2D)
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 50 "scanner.l"
T_RESERVED
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 51 "scanner.l"
T_RESERVED
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 52 "scanner.l"
T_RESERVED
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 54 "scanner.l"
T_RESERVED;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 57 "scanner.l"
T_RESERVED
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 58 "scanner.l"
T_RESERVED
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 59 "scanner.l"
T_RESERVED
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 60 "scanner.l"
T_RESERVED
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 61 "scanner.l"
T_RESERVED
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 62 "scanner.l"
T_RESERVED
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 63 "scanner.l"
T_RESERVED
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 65 "scanner.l"
T_RESERVED
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 66 "scanner.l"
T_RESERVED
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 67 "scanner.l"
T_RESERVED
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 68 "scanner.l"
T_RESERVED
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 69 "scanner.l"
T_RESERVED
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 70 "scanner.l"
T_RESERVED
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 72 "scanner.l"
T_RESERVED
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 73 "scanner.l"
T_RESERVED
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 74 "scanner.l"
T_RESERVED
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 75 "scanner.l"
T_RESERVED
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 76 "scanner.l"
T_RESERVED
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 77 "scanner.l"
T_RESERVED
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 79 "scanner.l"
PROCESS_NODATA(T_IN)
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 80 "scanner.l"
PROCESS_NODATA(T_OUT)
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 81 "scanner.l"
PROCESS_NODATA(T_INOUT)
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 83 "scanner.l"
PROCESS_NODATA(T_RETURN)
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 84 "scanner.l"
PROCESS_CHAR()
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 86 "scanner.l"
PROCESS_NODATA(T_OPERATOR)
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 87 "scanner.l"
PROCESS_NODATA(T_TYPEMAP)
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 88 "scanner.l"
PROCESS_NODATA(T_DEF_SPACE_ANO)
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 89 "scanner.l"
PROCESS_NODATA(T_DEF_DIM_ANO)
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 90 "scanner.l"
PROCESS_NODATA(T_DEFINE)
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 91 "scanner.l"
PROCESS_NODATA(T_BUILT_IN)
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 92 "scanner.l"
PROCESS_NODATA(T_CONVERNTION)
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 94 "scanner.l"
PROCESS_NODATA(T_GENERIC_DIMEN_NOTATION)
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 95 "scanner.l"
PROCESS_NODATA(T_GENERIC_SPACE_NOTATION)
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 97 "scanner.l"
PROCESS_CHAR()
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 98 "scanner.l"
PROCESS_CHAR()
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 99 "scanner.l"
PROCESS_CHAR()
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 100 "scanner.l"
PROCESS_CHAR()
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 101 "scanner.l"
PROCESS_CHAR()
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 102 "scanner.l"
PROCESS_CHAR()
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 104 "scanner.l"
PROCESS_CHAR()
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 105 "scanner.l"
PROCESS_CHAR()
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 106 "scanner.l"
PROCESS_CHAR()
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 107 "scanner.l"
PROCESS_CHAR()
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 109 "scanner.l"
PROCESS_NODATA(T_EQ)
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 110 "scanner.l"
PROCESS_CHAR()
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 111 "scanner.l"
PROCESS_CHAR()
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 112 "scanner.l"
PROCESS_NODATA(T_LE)
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 113 "scanner.l"
PROCESS_NODATA(T_GE)
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 115 "scanner.l"
PROCESS_CHAR()
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 116 "scanner.l"
PROCESS_CHAR()
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 117 "scanner.l"
PROCESS_CHAR()
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 118 "scanner.l"
PROCESS_CHAR()
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 120 "scanner.l"
PROCESS_NODATA(T_IF)
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 121 "scanner.l"
PROCESS_NODATA(T_ELSE)
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 122 "scanner.l"
PROCESS_NODATA(T_FOR)
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 124 "scanner.l"
PROCESS_TOKEN(T_LT_INT)
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 125 "scanner.l"
PROCESS_TOKEN(T_LT_INT)
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 126 "scanner.l"
PROCESS_TOKEN(T_LT_INT)
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 128 "scanner.l"
PROCESS_TOKEN(T_LT_FLT)
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 129 "scanner.l"
PROCESS_TOKEN(T_LT_FLT)
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 130 "scanner.l"
PROCESS_TOKEN(T_LT_FLT)
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 131 "scanner.l"
PROCESS_TOKEN(T_LT_FLT)
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 133 "scanner.l"
PROCESS_TOKEN(T_LT_BLN)
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 134 "scanner.l"
PROCESS_TOKEN(T_LT_BLN)
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 136 "scanner.l"
{
    string id = yytext;
    // if space anno?
    if(context::get_ctx()->state != context::SkipAnoId)
    {
        space_ano_it sit = context::get_ctx()->space_anos.find(id);
        if(sit != context::get_ctx()->space_anos.end())
        {
            yylval.space_ano = &sit->second;
            return T_SPACE_ANO;
        }

        dim_ano_it dit = context::get_ctx()->dim_anos.find(id);
        if(dit != context::get_ctx()->dim_anos.end())
        {
            yylval.dimen_ano = &dit->second;
            return T_DIMEN_ANO;
        }
    }
    typemap_it tit = context::get_ctx()->typemaps.find(id);
    if(tit != context::get_ctx()->typemaps.end())
    {
        yylval.str = new string(id);
        return T_BASIC_TYPE;
    }


    yylval.str = new string(id);
    return T_ID;
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 167 "scanner.l"
{  }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 168 "scanner.l"
{ }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 169 "scanner.l"
{ assert(false); return yytext[0]; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 171 "scanner.l"
BEGIN(comment);
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 172 "scanner.l"
/* eat anything that's not a '*' */
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 173 "scanner.l"
/* eat up '*' s not followed by '/'s */
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 174 "scanner.l"
BEGIN(INITIAL);
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 176 "scanner.l"
BEGIN(cpp_comment);
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 177 "scanner.l"

	YY_BREAK
case 91:
YY_RULE_SETUP
#line 178 "scanner.l"
BEGIN(INITIAL);
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 180 "scanner.l"
{ 
    BEGIN(raw_code); 
    raw_code_source = ""; 
    string input = yytext;
    int end = input.find_first_of('@', 1);
    yylval.str = new string(input.substr(1, end-1)); 
    return T_BUILT_IN_SIG; 
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 188 "scanner.l"
{ raw_code_source += " "; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 189 "scanner.l"
{ raw_code_source += yytext; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 190 "scanner.l"
{ 
    BEGIN(INITIAL); 
    yylval.str = new string(raw_code_source); 
    //printf("%s\n", raw_code_source.c_str()); 
    return T_RAW_CODE; 
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 198 "scanner.l"
ECHO;
	YY_BREAK
#line 1450 "D:/graphics/nprojects/safegi/final_pack/SafeGI/typed/libs/sparser/scanner.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(cpp_comment):
case YY_STATE_EOF(raw_code):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 394 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 394 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 393);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 198 "scanner.l"


void setup_buf(const std::string &in_src)
{
    yy_scan_string(in_src.c_str());
}

std::string get_str()
{
    return std::string(YY_CURRENT_BUFFER->yy_ch_buf);
}

void release_buf()
{
    yy_delete_buffer(YY_CURRENT_BUFFER);
}